source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-chirpy", "~> 7.2"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-archives", "~> 2.3"
gem "jekyll-redirect-from", "~> 0.16"
gem "jekyll-include-cache", "~> 0.2"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
